name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.1
  - mlflow=2.7.1
  - scikit-learn=1.3.1
  - matplotlib=3.7.3
  - pillow=10.0.1
  - pip=23.2.1
  - pip:
      - wandb==0.15.12